<#
.SYNOPSIS
Install or configure the Windows 2000 DDK for Phase 1.

.DESCRIPTION
This script validates tools/WIN2KDDK.EXE, optionally launches the installer,
checks for <DdkPath>\bin\setenv.bat, and writes local command wrappers for
debug/release build prompts and the DDK toaster sample build.

-DdkPath defaults to tools\ntddk inside this repository. The wrappers it
writes derive both the repository root and the DDK from their own location
(%~dp0), so they keep working after the repository is moved or renamed - the
the older wrappers baked absolute paths in and silently pointed at a
directory that no longer existed.
#>

[CmdletBinding()]
param(
    [string]$DdkPath = "",
    [string]$ToolsDir = "",
    [string]$LocalScriptDir = "",
    [switch]$RunInstaller
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "common.ps1")

$RepoRoot = Get-RepoRoot
if ([string]::IsNullOrWhiteSpace($ToolsDir)) {
    $ToolsDir = Get-DefaultToolsDir
}
if ([string]::IsNullOrWhiteSpace($DdkPath)) {
    $DdkPath = Get-DefaultDdkPath
}
if ([string]::IsNullOrWhiteSpace($LocalScriptDir)) {
    $LocalScriptDir = Get-DefaultLocalScriptDir
}

# The wrappers live in scripts\local\, so %~dp0..\.. is the repository root.
# Express the DDK against that when it is inside the repo; a DDK installed
# elsewhere has no relative form and is written out in full.
$ddkRel = Get-RelativePathFrom -FromDir $RepoRoot -To $DdkPath
if ($null -ne $ddkRel -and -not $ddkRel.StartsWith("..")) {
    $ddkExpr = "%REPO%\$ddkRel"
} else {
    $ddkExpr = $DdkPath
}

Write-Step "Checking host"
Test-SetupHost

Write-Step "Checking Win2K DDK installer"
$ddkExe = Join-Path $ToolsDir "WIN2KDDK.EXE"
if (-not (Test-Path -LiteralPath $ddkExe)) {
    throw "Missing $ddkExe"
}
Write-Ok "Found $ddkExe"

$setenvBat = Join-Path $DdkPath "bin\setenv.bat"
if (Test-Path -LiteralPath $setenvBat) {
    Write-Ok "Win2K DDK appears installed at $DdkPath"
} else {
    Write-Warn "Win2K DDK not detected at $DdkPath"
    if ($RunInstaller) {
        # The GUI installer writes wherever its own dialog says, which will not
        # be $DdkPath unless the operator types it - hence the note below.
        Write-Step "Launching Win2K DDK installer"
        Write-Warn "Point the installer at $DdkPath, or the wrappers written below will not find it."
        Start-Process -FilePath $ddkExe -Wait
    } else {
        Write-Warn "Installer was not launched, and is not needed. Unpack the DDK into"
        Write-Warn "the repository instead - no GUI, no machine-wide install:"
        Write-Warn "  powershell -ExecutionPolicy Bypass -File scripts\install-w2kddk-cabs.ps1"
    }
}

Write-Step "Writing DDK command wrappers"
Ensure-Directory $LocalScriptDir

# The standard -> release flavour rename renamed a wrapper this
# script generates, and generating the new name does not remove the old one -
# scripts\local is git-ignored, so an existing checkout keeps ddk-standard.cmd
# for as long as nothing deletes it, and a rerun leaves both. Audit round 6
# found that: a stale wrapper still works, which is what makes it worth
# removing rather than harmless - it is the flavour vocabulary surviving in the
# one place a grep of the tree cannot see.
$staleWrapper = Join-Path $LocalScriptDir "ddk-standard.cmd"
if (Test-Path -LiteralPath $staleWrapper) {
    Remove-Item -LiteralPath $staleWrapper -Force
    Write-Warn "Removed the pre-rename wrapper ddk-standard.cmd (now ddk-release.cmd)"
}

# Every wrapper opens the same way: locate the repository from the wrapper's
# own path (scripts\local\<file>.cmd), then the DDK relative to that.
$prologue = @(
    "@echo off",
    "rem Generated by scripts\setup-w2kddk.ps1. Paths are derived from this",
    "rem file's location, so moving or renaming the repository is not a fault.",
    "for %%I in (""%~dp0..\.."") do set ""REPO=%%~fI""",
    "set ""DDKROOT=$ddkExpr""",
    "if not exist ""%DDKROOT%\bin\setenv.bat"" (",
    "  echo Missing %DDKROOT%\bin\setenv.bat",
    "  echo Unpack the Windows 2000 DDK first:",
    "  echo   powershell -ExecutionPolicy Bypass -File ""%REPO%\scripts\install-w2kddk-cabs.ps1""",
    "  exit /b 1",
    ")"
)

$ddkDebug = Join-Path $LocalScriptDir "ddk-debug.cmd"
Write-AsciiFile $ddkDebug ($prologue + @(
    "rem setenv.bat uses %1 verbatim as BASEDIR - pass it unquoted or every",
    "rem derived path carries literal quotes and the build cannot find inc/lib.",
    "rem ""checked"" is the DDK's own word for what this project calls the debug build.",
    "call ""%DDKROOT%\bin\setenv.bat"" %DDKROOT% checked w2k x86",
    "cd /d ""%REPO%""",
    "echo.",
    "echo DDK debug build environment ready.",
    "echo When src exists: cd src && build",
    "cmd /k"
))

$ddkRelease = Join-Path $LocalScriptDir "ddk-release.cmd"
Write-AsciiFile $ddkRelease ($prologue + @(
    "rem setenv.bat uses %1 verbatim as BASEDIR - pass it unquoted (see ddk-debug).",
    "rem ""free"" is the DDK's own word for what this project calls the release build.",
    "call ""%DDKROOT%\bin\setenv.bat"" %DDKROOT% free w2k x86",
    "cd /d ""%REPO%""",
    "echo.",
    "echo DDK release build environment ready.",
    "echo When src exists: cd src && build",
    "cmd /k"
))

# The Win2K DDK ships toaster under src\general\toaster (not src\wdm\toaster;
# verified against NGEN_DDK.inf in the WIN2KDDK.EXE payload).
$verifyDdk = Join-Path $LocalScriptDir "verify-ddk-toaster.cmd"
Write-AsciiFile $verifyDdk ($prologue + @(
    "rem setenv.bat uses %1 verbatim as BASEDIR - pass it unquoted (see ddk-debug).",
    "rem ""checked"" is the DDK's own word for what this project calls the debug build.",
    "call ""%DDKROOT%\bin\setenv.bat"" %DDKROOT% checked w2k x86",
    "if not exist ""%DDKROOT%\src\general\toaster\func"" (",
    "  echo Missing sample path: %DDKROOT%\src\general\toaster\func",
    "  exit /b 1",
    ")",
    "cd /d ""%DDKROOT%\src\general\toaster\func""",
    "rem The DDK's own mofcomp.exe cannot CoCreate its COM class on modern",
    "rem Windows (0x8007007f); generate the binary MOF with the OS mofcomp.",
    "if not exist toaster.bmf %SystemRoot%\System32\wbem\mofcomp.exe -B:toaster.bmf toaster.mof",
    "build -cef",
    "pause"
))

Write-Ok "Wrote $ddkDebug"
Write-Ok "Wrote $ddkRelease"
Write-Ok "Wrote $verifyDdk"
