/*
 * hcd_rh.c - the root hub of xhci98.sys: the PDO the controller FDO creates,
 * and the FDO this driver attaches over it in its second role (roadmap-hcd.md
 * task 26-A.4; design record 13 sections 5.2 and 8.6).
 *
 * The root-hub PDO answers IRP_MN_QUERY_ID with XHCI98\ROOT_HUB and no
 * compatible id, so only this driver's own INF binds it - never usbhub.sys,
 * which a USB\ROOT_HUB* or hub-class compatible id would bring back on top of
 * the bus (section 8.6). Its FDO is this driver again, decided at AddDevice by
 * the PDO's driver object; that FDO's BusRelations are the bus's device PDOs,
 * every one a child of the root hub wherever it sits in the USB topology
 * (section 5.2).
 *
 * Lifetime, the WDM bus-driver rule: the root-hub PDO is deleted by the
 * controller FDO's remove, or by its own remove once the controller has
 * reported it missing - never by its own remove alone, which PnP sends on a
 * disable of the root hub while the controller still enumerates it.
 *
 * IRQL: PASSIVE_LEVEL throughout (PnP and power on DO_POWER_PAGABLE objects).
 */

#include "hcd.h"
#include "xhci_dbg.h"

static const WCHAR hcdRootHubId[] = L"XHCI98\\ROOT_HUB";
static const WCHAR hcdRootHubText[] = L"xhci98 USB 3.x Root Hub";

static LONG hcdRootHubSerial;

/* ----------------------------------------------------------------------- */
/* Helpers                                                                  */
/* ----------------------------------------------------------------------- */

static ULONG hcdWcsLen(const WCHAR *s)
{
    ULONG n;

    n = 0;
    while (s[n] != 0) {
        n++;
    }
    return n;
}

/* A copy of a string in handed-off pool, with one extra NUL when `multi` is
 * set (a REG_MULTI_SZ of one string). NULL on allocation failure. */
static PWCHAR hcdCopyId(const WCHAR *s, ULONG multi)
{
    PWCHAR out;
    ULONG n;
    ULONG i;

    n = hcdWcsLen(s);
    out = (PWCHAR)HcdPoolAllocHandedOff((n + 2) * sizeof(WCHAR));
    if (out == NULL) {
        return NULL;
    }
    for (i = 0; i < n; i++) {
        out[i] = s[i];
    }
    out[n] = 0;
    out[n + 1] = 0;
    UNREFERENCED_PARAMETER(multi);
    return out;
}

/* "\Device\XHCI98RH" plus a decimal serial: PDOs are named on NT, and
 * FILE_AUTOGENERATED_DEVICE_NAME is not a Windows 98 promise. */
static VOID hcdRootHubName(PWCHAR buffer, ULONG serial)
{
    static const WCHAR prefix[] = L"\\Device\\XHCI98RH";
    WCHAR digits[12];
    ULONG n;
    ULONG i;
    ULONG d;

    n = 0;
    for (i = 0; prefix[i] != 0; i++) {
        buffer[n++] = prefix[i];
    }
    d = 0;
    do {
        digits[d++] = (WCHAR)(L'0' + (serial % 10UL));
        serial /= 10UL;
    } while (serial != 0 && d < 11);
    while (d > 0) {
        buffer[n++] = digits[--d];
    }
    buffer[n] = 0;
}

/* ----------------------------------------------------------------------- */
/* The root-hub PDO, from the controller FDO's side                         */
/* ----------------------------------------------------------------------- */

/* Create the PDO once per controller, at its first successful start, and
 * have PnP ask for BusRelations. */
NTSTATUS HcdRootHubCreatePdo(PHCD_CONTROLLER hc)
{
    WCHAR nameBuffer[40];
    UNICODE_STRING name;
    PDEVICE_OBJECT pdo;
    PHCD_ROOTHUB_PDO ext;
    NTSTATUS status;

    if (hc->RootHubPdo != NULL) {
        return STATUS_SUCCESS;
    }

    hcdRootHubName(nameBuffer,
                   (ULONG)InterlockedIncrement(&hcdRootHubSerial));
    RtlInitUnicodeString(&name, nameBuffer);
    status = IoCreateDevice(HcdDriverObject, sizeof(HCD_ROOTHUB_PDO), &name,
                            FILE_DEVICE_BUS_EXTENDER, 0, FALSE, &pdo);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    ext = (PHCD_ROOTHUB_PDO)pdo->DeviceExtension;
    ext->Common.Kind = HCD_KIND_ROOTHUB_PDO;
    ext->Common.Self = pdo;
    ext->Common.PnpState = HCD_PNP_ADDED;
    ext->Common.DevicePower = PowerDeviceD0;
    ext->Common.SystemPower = PowerSystemWorking;
    ext->Controller = hc;

    pdo->Flags |= DO_POWER_PAGABLE;
    pdo->Flags &= ~DO_DEVICE_INITIALIZING;
    hc->RootHubPdo = pdo;

    XHCI_DBG_TEXT("hcd: root hub PDO created");
    IoInvalidateDeviceRelations(hc->Pdo, BusRelations);
    return STATUS_SUCCESS;
}

/* The controller's remove: the child goes with it. */
VOID HcdRootHubDeletePdo(PHCD_CONTROLLER hc)
{
    if (hc->RootHubPdo != NULL) {
        IoDeleteDevice(hc->RootHubPdo);
        hc->RootHubPdo = NULL;
    }
}

/*
 * IRP_MN_QUERY_DEVICE_RELATIONS / BusRelations at the controller FDO: the
 * relations a filter above may already have built, plus the root-hub PDO,
 * referenced as PnP requires. The IRP then goes down with the new list.
 */
NTSTATUS HcdControllerBusRelations(PHCD_CONTROLLER hc, PIRP irp)
{
    PDEVICE_RELATIONS old;
    PDEVICE_RELATIONS rel;
    ULONG count;
    ULONG i;

    if (hc->RootHubPdo == NULL) {
        return HcdPassDown(hc, irp);
    }

    old = (PDEVICE_RELATIONS)irp->IoStatus.Information;
    count = (old != NULL) ? old->Count : 0;
    rel = (PDEVICE_RELATIONS)HcdPoolAllocHandedOff(
        sizeof(DEVICE_RELATIONS) + count * sizeof(PDEVICE_OBJECT));
    if (rel == NULL) {
        return HcdCompleteIrp(irp, STATUS_INSUFFICIENT_RESOURCES,
                              irp->IoStatus.Information);
    }
    for (i = 0; i < count; i++) {
        rel->Objects[i] = old->Objects[i];
    }
    rel->Objects[count] = hc->RootHubPdo;
    rel->Count = count + 1;
    ObReferenceObject(hc->RootHubPdo);
    if (old != NULL) {
        HcdPoolFreeForeign(old);
    }

    irp->IoStatus.Information = (ULONG_PTR)rel;
    irp->IoStatus.Status = STATUS_SUCCESS;
    return HcdPassDown(hc, irp);
}

/* ----------------------------------------------------------------------- */
/* The root-hub PDO's own PnP and power                                     */
/* ----------------------------------------------------------------------- */

static NTSTATUS hcdRootHubQueryId(PIRP irp, BUS_QUERY_ID_TYPE type)
{
    PWCHAR id;

    switch (type) {
    case BusQueryDeviceID:
        id = hcdCopyId(hcdRootHubId, 0);
        break;
    case BusQueryHardwareIDs:
        id = hcdCopyId(hcdRootHubId, 1);
        break;
    case BusQueryInstanceID:
        id = hcdCopyId(L"0", 0);
        break;
    default:
        /* No compatible id, by design (section 8.6): the IRP keeps the
         * status it arrived with. */
        return HcdCompleteIrp(irp, irp->IoStatus.Status,
                              irp->IoStatus.Information);
    }
    if (id == NULL) {
        return HcdCompleteIrp(irp, STATUS_INSUFFICIENT_RESOURCES, 0);
    }
    return HcdCompleteIrp(irp, STATUS_SUCCESS, (ULONG_PTR)id);
}

static NTSTATUS hcdRootHubCapabilities(PIRP irp)
{
    PIO_STACK_LOCATION stack;
    PDEVICE_CAPABILITIES caps;
    ULONG i;

    stack = IoGetCurrentIrpStackLocation(irp);
    caps = stack->Parameters.DeviceCapabilities.Capabilities;
    if (caps->Version != 1 || caps->Size < sizeof(DEVICE_CAPABILITIES)) {
        return HcdCompleteIrp(irp, STATUS_UNSUCCESSFUL, 0);
    }
    caps->DeviceD1 = FALSE;
    caps->DeviceD2 = FALSE;
    caps->LockSupported = FALSE;
    caps->EjectSupported = FALSE;
    caps->Removable = FALSE;
    caps->DockDevice = FALSE;
    caps->UniqueID = FALSE;
    caps->SilentInstall = FALSE;
    caps->RawDeviceOK = FALSE;
    caps->SurpriseRemovalOK = FALSE;
    caps->Address = 0;
    caps->UINumber = 0;
    caps->DeviceState[PowerSystemWorking] = PowerDeviceD0;
    for (i = PowerSystemSleeping1; i < PowerSystemMaximum; i++) {
        caps->DeviceState[i] = PowerDeviceD3;
    }
    caps->SystemWake = PowerSystemUnspecified;
    caps->DeviceWake = PowerDeviceUnspecified;
    return HcdCompleteIrp(irp, STATUS_SUCCESS, 0);
}

NTSTATUS HcdRootHubPdoPnp(PHCD_ROOTHUB_PDO pdo, PIRP irp)
{
    PIO_STACK_LOCATION stack;
    PWCHAR text;

    stack = IoGetCurrentIrpStackLocation(irp);
    XHCI_DBG_VALUE("hcd: root hub PDO PnP minor", stack->MinorFunction);

    switch (stack->MinorFunction) {
    case IRP_MN_START_DEVICE:
        pdo->Started = 1;
        pdo->Common.PnpState = HCD_PNP_STARTED;
        return HcdCompleteIrp(irp, STATUS_SUCCESS, 0);

    case IRP_MN_QUERY_STOP_DEVICE:
    case IRP_MN_QUERY_REMOVE_DEVICE:
    case IRP_MN_CANCEL_STOP_DEVICE:
    case IRP_MN_CANCEL_REMOVE_DEVICE:
        return HcdCompleteIrp(irp, STATUS_SUCCESS, 0);

    case IRP_MN_STOP_DEVICE:
    case IRP_MN_SURPRISE_REMOVAL:
        pdo->Started = 0;
        pdo->Common.PnpState = HCD_PNP_STOPPED;
        return HcdCompleteIrp(irp, STATUS_SUCCESS, 0);

    case IRP_MN_REMOVE_DEVICE:
        pdo->Started = 0;
        pdo->Common.PnpState = HCD_PNP_REMOVED;
        if (pdo->ReportedMissing) {
            pdo->Controller->RootHubPdo = NULL;
            HcdCompleteIrp(irp, STATUS_SUCCESS, 0);
            IoDeleteDevice(pdo->Common.Self);
            return STATUS_SUCCESS;
        }
        return HcdCompleteIrp(irp, STATUS_SUCCESS, 0);

    case IRP_MN_QUERY_ID:
        return hcdRootHubQueryId(irp, stack->Parameters.QueryId.IdType);

    case IRP_MN_QUERY_DEVICE_TEXT:
        if (stack->Parameters.QueryDeviceText.DeviceTextType ==
            DeviceTextDescription) {
            text = hcdCopyId(hcdRootHubText, 0);
            if (text == NULL) {
                return HcdCompleteIrp(irp, STATUS_INSUFFICIENT_RESOURCES, 0);
            }
            return HcdCompleteIrp(irp, STATUS_SUCCESS, (ULONG_PTR)text);
        }
        return HcdCompleteIrp(irp, irp->IoStatus.Status,
                              irp->IoStatus.Information);

    case IRP_MN_QUERY_CAPABILITIES:
        return hcdRootHubCapabilities(irp);

    case IRP_MN_QUERY_PNP_DEVICE_STATE:
        return HcdCompleteIrp(irp, STATUS_SUCCESS,
                              irp->IoStatus.Information);

    case IRP_MN_QUERY_DEVICE_RELATIONS:
        if (stack->Parameters.QueryDeviceRelations.Type ==
            TargetDeviceRelation) {
            PDEVICE_RELATIONS rel;

            rel = (PDEVICE_RELATIONS)HcdPoolAllocHandedOff(
                sizeof(DEVICE_RELATIONS));
            if (rel == NULL) {
                return HcdCompleteIrp(irp, STATUS_INSUFFICIENT_RESOURCES, 0);
            }
            rel->Count = 1;
            rel->Objects[0] = pdo->Common.Self;
            ObReferenceObject(pdo->Common.Self);
            return HcdCompleteIrp(irp, STATUS_SUCCESS, (ULONG_PTR)rel);
        }
        /* BusRelations were filled by the root-hub FDO above, if any; a PDO
         * keeps whatever arrived. */
        return HcdCompleteIrp(irp, irp->IoStatus.Status,
                              irp->IoStatus.Information);

    default:
        /* Resources, requirements, bus information and the rest: a PDO with
         * nothing to say completes with the status the IRP arrived with. */
        return HcdCompleteIrp(irp, irp->IoStatus.Status,
                              irp->IoStatus.Information);
    }
}

NTSTATUS HcdRootHubPdoPower(PHCD_ROOTHUB_PDO pdo, PIRP irp)
{
    PIO_STACK_LOCATION stack;
    NTSTATUS status;

    stack = IoGetCurrentIrpStackLocation(irp);
    status = irp->IoStatus.Status;
    if (stack->MinorFunction == IRP_MN_SET_POWER) {
        if (stack->Parameters.Power.Type == DevicePowerState) {
            pdo->Common.DevicePower =
                stack->Parameters.Power.State.DeviceState;
            (VOID)PoSetPowerState(pdo->Common.Self, DevicePowerState,
                                  stack->Parameters.Power.State);
        } else {
            pdo->Common.SystemPower =
                stack->Parameters.Power.State.SystemState;
        }
        status = STATUS_SUCCESS;
    } else if (stack->MinorFunction == IRP_MN_QUERY_POWER) {
        status = STATUS_SUCCESS;
    } else if (stack->MinorFunction == IRP_MN_WAIT_WAKE) {
        status = STATUS_NOT_SUPPORTED;
    }
    PoStartNextPowerIrp(irp);
    return HcdCompleteIrp(irp, status, irp->IoStatus.Information);
}

/* ----------------------------------------------------------------------- */
/* The root-hub FDO                                                         */
/* ----------------------------------------------------------------------- */

static ULONG hcdRhIoEnter(PHCD_ROOTHUB_FDO fdo)
{
    (VOID)InterlockedIncrement(&fdo->OutstandingIo);
    if (fdo->Common.PnpState == HCD_PNP_REMOVED) {
        if (InterlockedDecrement(&fdo->OutstandingIo) == 0) {
            (VOID)KeSetEvent(&fdo->RemoveEvent, IO_NO_INCREMENT, FALSE);
        }
        return 0;
    }
    return 1;
}

static VOID hcdRhIoLeave(PHCD_ROOTHUB_FDO fdo)
{
    if (InterlockedDecrement(&fdo->OutstandingIo) == 0) {
        (VOID)KeSetEvent(&fdo->RemoveEvent, IO_NO_INCREMENT, FALSE);
    }
}

static NTSTATUS hcdRhPassDown(PHCD_ROOTHUB_FDO fdo, PIRP irp)
{
    IoSkipCurrentIrpStackLocation(irp);
    return IoCallDriver(fdo->LowerDevice, irp);
}

static NTSTATUS NTAPI hcdRhSignal(PDEVICE_OBJECT DeviceObject, PIRP Irp,
                                  PVOID Context)
{
    UNREFERENCED_PARAMETER(DeviceObject);
    UNREFERENCED_PARAMETER(Irp);

    (VOID)KeSetEvent((PKEVENT)Context, IO_NO_INCREMENT, FALSE);
    return STATUS_MORE_PROCESSING_REQUIRED;
}

/* AddDevice for a PDO this driver created: the root hub's FDO. */
NTSTATUS HcdRootHubAddDevice(PDRIVER_OBJECT driver, PDEVICE_OBJECT pdo)
{
    PHCD_ROOTHUB_PDO pdoExt;
    PDEVICE_OBJECT fdo;
    PHCD_ROOTHUB_FDO ext;
    NTSTATUS status;

    pdoExt = (PHCD_ROOTHUB_PDO)pdo->DeviceExtension;
    if (pdoExt->Common.Kind != HCD_KIND_ROOTHUB_PDO) {
        return STATUS_NOT_SUPPORTED;
    }

    status = IoCreateDevice(driver, sizeof(HCD_ROOTHUB_FDO), NULL,
                            FILE_DEVICE_BUS_EXTENDER, 0, FALSE, &fdo);
    if (!NT_SUCCESS(status)) {
        return status;
    }
    ext = (PHCD_ROOTHUB_FDO)fdo->DeviceExtension;
    ext->Common.Kind = HCD_KIND_ROOTHUB_FDO;
    ext->Common.Self = fdo;
    ext->Common.PnpState = HCD_PNP_ADDED;
    ext->Common.DevicePower = PowerDeviceD0;
    ext->Common.SystemPower = PowerSystemWorking;
    ext->Pdo = pdo;
    ext->Controller = pdoExt->Controller;
    ext->OutstandingIo = 1;
    KeInitializeEvent(&ext->RemoveEvent, NotificationEvent, FALSE);

    ext->LowerDevice = IoAttachDeviceToDeviceStack(fdo, pdo);
    if (ext->LowerDevice == NULL) {
        IoDeleteDevice(fdo);
        return STATUS_NO_SUCH_DEVICE;
    }
    fdo->Flags |= DO_POWER_PAGABLE;
    fdo->Flags &= ~DO_DEVICE_INITIALIZING;
    XHCI_DBG_TEXT("hcd: root hub FDO attached");
    return STATUS_SUCCESS;
}

NTSTATUS HcdRootHubFdoPnp(PHCD_ROOTHUB_FDO fdo, PIRP irp)
{
    PIO_STACK_LOCATION stack;
    KEVENT done;
    NTSTATUS status;

    stack = IoGetCurrentIrpStackLocation(irp);
    XHCI_DBG_VALUE("hcd: root hub FDO PnP minor", stack->MinorFunction);

    if (stack->MinorFunction == IRP_MN_REMOVE_DEVICE) {
        fdo->Common.PnpState = HCD_PNP_REMOVED;
        hcdRhIoLeave(fdo);
        (VOID)KeWaitForSingleObject(&fdo->RemoveEvent, Executive, KernelMode,
                                    FALSE, NULL);
        irp->IoStatus.Status = STATUS_SUCCESS;
        status = hcdRhPassDown(fdo, irp);
        IoDetachDevice(fdo->LowerDevice);
        IoDeleteDevice(fdo->Common.Self);
        return status;
    }

    if (!hcdRhIoEnter(fdo)) {
        return HcdCompleteIrp(irp, STATUS_DELETE_PENDING, 0);
    }

    if (stack->MinorFunction == IRP_MN_START_DEVICE) {
        KeInitializeEvent(&done, NotificationEvent, FALSE);
        IoCopyCurrentIrpStackLocationToNext(irp);
        HCD_SET_COMPLETION_ALWAYS(irp, hcdRhSignal, &done);
        status = IoCallDriver(fdo->LowerDevice, irp);
        if (status == STATUS_PENDING) {
            (VOID)KeWaitForSingleObject(&done, Executive, KernelMode, FALSE,
                                        NULL);
        }
        status = irp->IoStatus.Status;
        if (NT_SUCCESS(status)) {
            fdo->Common.PnpState = HCD_PNP_STARTED;
        }
        status = HcdCompleteIrp(irp, status, 0);
        hcdRhIoLeave(fdo);
        return status;
    }

    switch (stack->MinorFunction) {
    case IRP_MN_STOP_DEVICE:
        fdo->Common.PnpState = HCD_PNP_STOPPED;
        irp->IoStatus.Status = STATUS_SUCCESS;
        break;
    case IRP_MN_SURPRISE_REMOVAL:
        fdo->Common.PnpState = HCD_PNP_SURPRISE_REMOVED;
        irp->IoStatus.Status = STATUS_SUCCESS;
        break;
    case IRP_MN_QUERY_STOP_DEVICE:
    case IRP_MN_QUERY_REMOVE_DEVICE:
    case IRP_MN_CANCEL_STOP_DEVICE:
    case IRP_MN_CANCEL_REMOVE_DEVICE:
        irp->IoStatus.Status = STATUS_SUCCESS;
        break;
    default:
        /* BusRelations: no device PDO exists before 26-A.4's enumeration,
         * so the root hub's list goes down as it arrived. */
        break;
    }
    status = hcdRhPassDown(fdo, irp);
    hcdRhIoLeave(fdo);
    return status;
}

NTSTATUS HcdRootHubFdoPower(PHCD_ROOTHUB_FDO fdo, PIRP irp)
{
    NTSTATUS status;

    if (!hcdRhIoEnter(fdo)) {
        PoStartNextPowerIrp(irp);
        return HcdCompleteIrp(irp, STATUS_DELETE_PENDING, 0);
    }
    PoStartNextPowerIrp(irp);
    IoSkipCurrentIrpStackLocation(irp);
    status = PoCallDriver(fdo->LowerDevice, irp);
    hcdRhIoLeave(fdo);
    return status;
}
